import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Text, Spinner } from "@chakra-ui/react";

import { useSession } from "next-auth/client";

const Home = () => {
  const [session, loading] = useSession();
  return (
    <div className={styles.container}>
      <Head>
        <title>Badge Endpoint!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          <Text fontSize="5xl">Customize Your Skills</Text>
        </h3>
        <Text pt={3} fontSize="xl">
          GitHub Profile Badge Endpoint
        </Text>

        {loading && <Spinner mt={5} />}

        {session && (
          <>
            <Text pt={3} color="linkedin.100">
              <small> Signed in as {session.user.name}</small>
            </Text>
          </>
        )}

        {!session && (
          <>
            <Text pt={3} mb={5} color="linkedin.100">
              <small>Please Sign in with Google Account</small>
            </Text>
          </>
        )}
      </main>
    </div>
  );
};

export default Home;
